# Cloud Run Job Configuration for Embedding Generation
# 
# This job can be created and executed to generate embeddings for products in production.
#
# Usage:
#   gcloud run jobs create generate-embeddings \
#     --source . \
#     --region asia-south2 \
#     --task-timeout 3600 \
#     --max-retries 1 \
#     --task-service-account github-actions-deploy@broadway-chatbot.iam.gserviceaccount.com \
#     --set-env-vars NODE_ENV=production \
#     --set-secrets DATABASE_URL=PRIVATE_DATABASE_URL:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest \
#     --vpc-network chatbot-vpc \
#     --vpc-subnet chatbot-subnet \
#     --vpc-egress private-ranges-only \
#     --memory 4Gi \
#     --cpu 2 \
#     --command node \
#     --args dist/scripts/generateEmbeddings.js
#
# Execute the job:
#   gcloud run jobs execute generate-embeddings --region asia-south2 --wait

apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: generate-embeddings
  labels:
    cloud.googleapis.com/location: asia-south2
spec:
  template:
    spec:
      template:
        spec:
          serviceAccountName: github-actions-deploy@broadway-chatbot.iam.gserviceaccount.com
          containers:
          - name: generate-embeddings
            image: asia-south2-docker.pkg.dev/broadway-chatbot/broadway-chatbot/broadway-chatbot:latest
            command: ["node"]
            args: ["dist/scripts/generateEmbeddings.js"]
            env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: PRIVATE_DATABASE_URL
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: OPENAI_API_KEY
            resources:
              limits:
                cpu: "2"
                memory: 4Gi
          restartPolicy: Never
          timeoutSeconds: 3600
          maxRetries: 1
      backoffLimit: 1

